// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function Button(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  var value = Props.value;
  var style = Props.style;
  return React.createElement("button", {
              style: Belt_Option.getWithDefault(style, {}),
              onClick: (function (param) {
                  return Curry._1(onClick, value);
                })
            }, label);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
