// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Display(Props) {
  var values = Props.values;
  return React.createElement("div", {
              style: {
                backgroundColor: "#a3a365",
                border: "4px solid gray",
                height: ".75rem",
                padding: "1rem",
                boxShadow: "border-box"
              }
            }, values.join(""));
}

var make = Display;

export {
  make ,
  
}
/* react Not a pure module */
