// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.bs.js";

function Pad(Props) {
  var gatherValue = Props.gatherValue;
  var compute = Props.compute;
  var clear = Props.clear;
  return React.createElement("div", undefined, React.createElement("div", {
                  style: {
                    display: "flex"
                  }
                }, React.createElement(Button.make, {
                      label: "1",
                      onClick: gatherValue,
                      value: "1"
                    }), React.createElement(Button.make, {
                      label: "2",
                      onClick: gatherValue,
                      value: "2"
                    }), React.createElement(Button.make, {
                      label: "3",
                      onClick: gatherValue,
                      value: "3"
                    }), React.createElement(Button.make, {
                      label: "-",
                      onClick: gatherValue,
                      value: "-"
                    })), React.createElement("div", {
                  style: {
                    display: "flex"
                  }
                }, React.createElement(Button.make, {
                      label: "4",
                      onClick: gatherValue,
                      value: "4"
                    }), React.createElement(Button.make, {
                      label: "5",
                      onClick: gatherValue,
                      value: "5"
                    }), React.createElement(Button.make, {
                      label: "6",
                      onClick: gatherValue,
                      value: "6"
                    }), React.createElement(Button.make, {
                      label: "+",
                      onClick: gatherValue,
                      value: "+"
                    })), React.createElement("div", {
                  style: {
                    display: "flex"
                  }
                }, React.createElement(Button.make, {
                      label: "7",
                      onClick: gatherValue,
                      value: "7"
                    }), React.createElement(Button.make, {
                      label: "8",
                      onClick: gatherValue,
                      value: "8"
                    }), React.createElement(Button.make, {
                      label: "9",
                      onClick: gatherValue,
                      value: "9"
                    }), React.createElement(Button.make, {
                      label: "*",
                      onClick: gatherValue,
                      value: "*"
                    })), React.createElement("div", {
                  style: {
                    display: "flex"
                  }
                }, React.createElement(Button.make, {
                      label: "0",
                      onClick: gatherValue,
                      value: "0"
                    }), React.createElement(Button.make, {
                      label: "C",
                      onClick: clear,
                      value: "C"
                    }), React.createElement(Button.make, {
                      label: "=",
                      onClick: compute,
                      value: "="
                    }), React.createElement(Button.make, {
                      label: "/",
                      onClick: gatherValue,
                      value: "/"
                    })));
}

var make = Pad;

export {
  make ,
  
}
/* react Not a pure module */
