// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var foo = [
  1,
  2,
  3
];

var x = Belt_Option.getWithDefault(Belt_Array.get(foo, -1), 9);

console.log("result: ", x);

export {
  foo ,
  x ,
  
}
/* x Not a pure module */
